{{- $runtimeConfigMapName := default (printf "%s-runtime-config" .Release.Name) .Values.runtimeConfigMap.name -}}
{{- if .Values.runtimeConfigMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $runtimeConfigMapName }}
  labels:
    app: {{ .Release.Name }}
data:
  runtime-config.js: |
    window.__APP_CONFIG__ = {
      API_BASE_URL: {{ .Values.runtimeConfig.apiBaseUrl | quote }},
      GRAFANA_PROXY_URL: {{ .Values.runtimeConfig.grafanaProxyUrl | quote }}
    };
{{- end }}
