image:
  repository: wearables42/web-frontend
  tag: "1.0.0"
  pullPolicy: Always

runtimeConfigMap:
  create: true
  name: ""

runtimeConfig:
  apiBaseUrl: "http://localhost:3001/api"
  grafanaProxyUrl: "http://localhost:3002/grafana-proxy"
  socketUrl: "http://localhost:3001"

# Service configuration
service:
  port: 80
  targetPort: 80

# Ingress configuration
ingress:
  enabled: false
  host: "wearables.charite.de"
  path: "/"
  certificateSecretName: "wearables-tls"

# Resource requests and limits
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

# Replica count
replicaCount: 1
