service:
  web:
    type: LoadBalancer
    loadBalancerIP: "194.94.4.68"
    annotations:
      loadbalancer.openstack.org/member-subnet-id: "f36c7488-2bc4-4171-bc7d-25e0cca40c9e"
      loadbalancer.openstack.org/network-id: "a33fd200-d1c7-4e7a-b496-a0302db68560"
      loadbalancer.openstack.org/subnet-id: "bd8ffe1c-2611-48b9-bace-280e64215bb5"

  websecure:
    type: LoadBalancer
    loadBalancerIP: "194.94.4.68"
    annotations:
      loadbalancer.openstack.org/member-subnet-id: "f36c7488-2bc4-4171-bc7d-25e0cca40c9e"
      loadbalancer.openstack.org/network-id: "a33fd200-d1c7-4e7a-b496-a0302db68560"
      loadbalancer.openstack.org/subnet-id: "bd8ffe1c-2611-48b9-bace-280e64215bb5"

ports:
  web:
    port: 80
    hostPort: 80
    expose: true
    exposedPort: 80
    protocol: TCP

  websecure:
    port: 443
    hostPort: 443
    expose: true
    exposedPort: 443
    protocol: TCP
    tls:
      enabled: true