replicaCount: 1

image:
  repository: infisical/infisical
  pullPolicy: IfNotPresent
  tag: "latest"

# External PostgreSQL (prod-postgres)
externalPostgres:
  host: prod-postgres.prod-postgres.svc.cluster.local
  port: 5432
  database: infisical
  username: infisical
  password: jORRK2BWkVIOZtvP1aioBUnzKfF4PLWR

valkey:
  enabled: true
  image:
    repository: valkey/valkey
    tag: "8-alpine"
  # Valkey läuft im Memory-Only Modus ohne PVC (als Cache)
  persistence:
    enabled: false

infisical:
  # Infisical configuration
  siteUrl: "https://wearables.charite.de/infisical"
  encryptionKey: "7d58f02b08d229a102081a2936dbed82"
  jwtAuthSecret: "pKi7vsPfaupBetCLvVbim+ymP8y0qrUsgaS9H9FLorc="
  jwtRefreshSecret: "0Ywau83zNDgmXgUdQLVFk4dPRVmoOJIPAcCSuRNpAPE="
  jwtServiceSecret: "QtxlCok7+cBiiIFxOZ1WVrAFmYJVtouLRi15kaYs88A="

service:
  type: ClusterIP
  port: 8080
  nodePort: 30080

ingress:
  enabled: true
  host: wearables.charite.de
  prefix: /infisical

certificate:
  secretName: wearables-tls
