apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Release.Name }}-volume"
  labels:
    app: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.postgres.storageClassName }}
  capacity:
    storage: {{ .Values.postgres.storageSize }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql