apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretRef }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.user | required "postgres.user must be set in values" | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | required "postgres.password must be set in values" | quote }}
  POSTGRES_DB: {{ .Values.postgres.db | required "postgres.db must be set in values" | quote }}
