port: 8125
replicas: 3

image:
  repository: telegraf
  tag: 1.36
  pullPolicy: IfNotPresent

config:
  kafkaConsumer: 
    name: kafka
    namespace: kafka
    version: 4.1.0
    topics:
    - wearables-lp
  influxProducer:
    name: influxdb      #name of influx (without service or deployment) 
    namespace: influx   #namespace influx is deployed in
    port: 8086          #open influx port
    org: ""
    bucket: ""
    token: ""

