apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mySecrets.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  # postgres_conn: {{ required "A valid dbConnectionString is required!" .Values.mySecrets.dbConnectionString }}
  lakefs_auth_encrypt: {{ required "A valid authEncryptSecret is required!" .Values.mySecrets.authEncryptSecret }}