apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mySecrets.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  authEncryptSecretKey: {{ required "A valid authEncryptSecretKey is required!" .Values.mySecrets.authEncryptSecretKey }}
  databaseConnectionString: {{ required "A valid databaseConnectionString is required!" .Values.mySecrets.databaseConnectionString }}
  s3AccessKey: {{ required "A valid s3AccessKey is required!" .Values.mySecrets.s3AccessKey }}
  s3SecretKey: {{ required "A valid s3SecretKey is required!" .Values.mySecrets.s3SecretKey }}
