apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.custom_lakefs_secrets.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  auth_encrypt_secret_key: {{ required "The auth_encrypt_secret_key is required. Check if you have set it in my-secrets.yaml" .Values.custom_lakefs_secrets.auth_encrypt_secret_key | quote }}
  database_connection_string: {{ required "The database_connection_string is required. Check if you have set it in my-secrets.yaml" .Values.custom_lakefs_secrets.database_connection_string | quote }}
  s3_access_key: {{ required "The s3_access_key is required. Check if you have set it in my-secrets.yaml" .Values.custom_lakefs_secrets.s3_access_key | quote }}
  s3_secret_key: {{ required "The s3_secret_key is required. Check if you have set it in my-secrets.yaml" .Values.custom_lakefs_secrets.s3_secret_key | quote }}
  lakefs_s3_access_key: {{ required "The lakefs_s3_access_key is required. Check if you have set it in my-secrets.yaml" .Values.custom_lakefs_secrets.lakefs_s3_access_key | quote }}
  lakefs_s3_secret_key: {{ required "The lakefs_s3_secret_key is required. Check if you have set it in my-secrets.yaml" .Values.custom_lakefs_secrets.lakefs_s3_secret_key | quote }}
  lakefs_first_user_display_name: {{ required "The lakefs_first_user_display_name is required. Check if you have set it in my-secrets.yaml" .Values.custom_lakefs_secrets.lakefs_first_user_display_name | quote }}
