/* tslint:disable */
/* eslint-disable */
/**
 * Patient & Case API
 * Endpoints for fetching read-only Hospital cases and managing internal patients/cases.  ## Frontend Flow 1. Enter a Hospital case ID (hospitalCaseId) 2. Fetch and display the external Hospital case 3. User clicks \"Create Case\" to create an internal case 4. Show that patient/case was created and store the caseId 5. Display the case token as QR code for scanning in the Hospital app  ## Existing Patient Access 1. Fetch all internal patients/cases 2. User selects a patient/case to view details 3. Display case details and show case token as QR code  ## App Flow 1. Receive a caseToken scanned from Hospital app 2. Fetch the internal case using POST /cases/verify-token 3. Display case details 4. Allow user to proceed with further actions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Case,
  CaseCreated,
  CaseVerified,
  CasesFromHospitalCasePostRequest,
  CasesVerifyTokenPostRequest,
} from '../models/index';
import {
    CaseFromJSON,
    CaseToJSON,
    CaseCreatedFromJSON,
    CaseCreatedToJSON,
    CaseVerifiedFromJSON,
    CaseVerifiedToJSON,
    CasesFromHospitalCasePostRequestFromJSON,
    CasesFromHospitalCasePostRequestToJSON,
    CasesVerifyTokenPostRequestFromJSON,
    CasesVerifyTokenPostRequestToJSON,
} from '../models/index';

export interface CasesCaseIdGetRequest {
    caseId: string;
}

export interface CasesFromHospitalCasePostOperationRequest {
    casesFromHospitalCasePostRequest: CasesFromHospitalCasePostRequest;
}

export interface CasesVerifyTokenPostOperationRequest {
    casesVerifyTokenPostRequest: CasesVerifyTokenPostRequest;
}

/**
 * CasesApi - interface
 * 
 * @export
 * @interface CasesApiInterface
 */
export interface CasesApiInterface {
    /**
     * Returns a single internal case by ID
     * @summary Get a single case
     * @param {string} caseId Internal case identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CasesApiInterface
     */
    casesCaseIdGetRaw(requestParameters: CasesCaseIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Case>>;

    /**
     * Returns a single internal case by ID
     * Get a single case
     */
    casesCaseIdGet(requestParameters: CasesCaseIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Case>;

    /**
     * Creates an internal case from an external Hospital case with the specified conflict-resolution rules.
     * @summary Create internal case from Hospital case
     * @param {CasesFromHospitalCasePostRequest} casesFromHospitalCasePostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CasesApiInterface
     */
    casesFromHospitalCasePostRaw(requestParameters: CasesFromHospitalCasePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CaseCreated>>;

    /**
     * Creates an internal case from an external Hospital case with the specified conflict-resolution rules.
     * Create internal case from Hospital case
     */
    casesFromHospitalCasePost(requestParameters: CasesFromHospitalCasePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CaseCreated>;

    /**
     * Returns a list of all internal cases
     * @summary List all internal cases
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CasesApiInterface
     */
    casesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Case>>>;

    /**
     * Returns a list of all internal cases
     * List all internal cases
     */
    casesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Case>>;

    /**
     * Verifies a case token and returns the linked case information
     * @summary Verify a case token
     * @param {CasesVerifyTokenPostRequest} casesVerifyTokenPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CasesApiInterface
     */
    casesVerifyTokenPostRaw(requestParameters: CasesVerifyTokenPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CaseVerified>>;

    /**
     * Verifies a case token and returns the linked case information
     * Verify a case token
     */
    casesVerifyTokenPost(requestParameters: CasesVerifyTokenPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CaseVerified>;

}

/**
 * 
 */
export class CasesApi extends runtime.BaseAPI implements CasesApiInterface {

    /**
     * Returns a single internal case by ID
     * Get a single case
     */
    async casesCaseIdGetRaw(requestParameters: CasesCaseIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Case>> {
        if (requestParameters['caseId'] == null) {
            throw new runtime.RequiredError(
                'caseId',
                'Required parameter "caseId" was null or undefined when calling casesCaseIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/cases/{caseId}`;
        urlPath = urlPath.replace(`{${"caseId"}}`, encodeURIComponent(String(requestParameters['caseId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CaseFromJSON(jsonValue));
    }

    /**
     * Returns a single internal case by ID
     * Get a single case
     */
    async casesCaseIdGet(requestParameters: CasesCaseIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Case> {
        const response = await this.casesCaseIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates an internal case from an external Hospital case with the specified conflict-resolution rules.
     * Create internal case from Hospital case
     */
    async casesFromHospitalCasePostRaw(requestParameters: CasesFromHospitalCasePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CaseCreated>> {
        if (requestParameters['casesFromHospitalCasePostRequest'] == null) {
            throw new runtime.RequiredError(
                'casesFromHospitalCasePostRequest',
                'Required parameter "casesFromHospitalCasePostRequest" was null or undefined when calling casesFromHospitalCasePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/cases/from-hospital-case`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CasesFromHospitalCasePostRequestToJSON(requestParameters['casesFromHospitalCasePostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CaseCreatedFromJSON(jsonValue));
    }

    /**
     * Creates an internal case from an external Hospital case with the specified conflict-resolution rules.
     * Create internal case from Hospital case
     */
    async casesFromHospitalCasePost(requestParameters: CasesFromHospitalCasePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CaseCreated> {
        const response = await this.casesFromHospitalCasePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a list of all internal cases
     * List all internal cases
     */
    async casesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Case>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/cases`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CaseFromJSON));
    }

    /**
     * Returns a list of all internal cases
     * List all internal cases
     */
    async casesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Case>> {
        const response = await this.casesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Verifies a case token and returns the linked case information
     * Verify a case token
     */
    async casesVerifyTokenPostRaw(requestParameters: CasesVerifyTokenPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CaseVerified>> {
        if (requestParameters['casesVerifyTokenPostRequest'] == null) {
            throw new runtime.RequiredError(
                'casesVerifyTokenPostRequest',
                'Required parameter "casesVerifyTokenPostRequest" was null or undefined when calling casesVerifyTokenPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/cases/verify-token`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CasesVerifyTokenPostRequestToJSON(requestParameters['casesVerifyTokenPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CaseVerifiedFromJSON(jsonValue));
    }

    /**
     * Verifies a case token and returns the linked case information
     * Verify a case token
     */
    async casesVerifyTokenPost(requestParameters: CasesVerifyTokenPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CaseVerified> {
        const response = await this.casesVerifyTokenPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
