/* tslint:disable */
/* eslint-disable */
/**
 * Patient & Case API
 * Endpoints for fetching read-only Charité cases and managing internal patients/cases.  ## Frontend Flow 1. Enter a Charité case ID (cCaseId) 2. Fetch and display the external Charité case 3. User clicks \"Create Case\" to create an internal case 4. Show that patient/case was created and store the caseId 5. Display the case token as QR code for scanning in the Charité app  ## Existing Patient Access 1. Fetch all internal patients/cases 2. User selects a patient/case to view details 3. Display case details and show case token as QR code  ## App Flow 1. Receive a caseToken scanned from Charité app 2. Fetch the internal case using POST /cases/verify-token 3. Display case details 4. Allow user to proceed with further actions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChariteCase,
} from '../models/index';
import {
    ChariteCaseFromJSON,
    ChariteCaseToJSON,
} from '../models/index';

export interface ChariteCasesCCaseIdGetRequest {
    cCaseId: string;
}

/**
 * CharitCasesApi - interface
 * 
 * @export
 * @interface CharitCasesApiInterface
 */
export interface CharitCasesApiInterface {
    /**
     * Returns a read-only Charité case by ID
     * @summary Get a Charité case
     * @param {string} cCaseId Charité case identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CharitCasesApiInterface
     */
    chariteCasesCCaseIdGetRaw(requestParameters: ChariteCasesCCaseIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChariteCase>>;

    /**
     * Returns a read-only Charité case by ID
     * Get a Charité case
     */
    chariteCasesCCaseIdGet(requestParameters: ChariteCasesCCaseIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChariteCase>;

}

/**
 * 
 */
export class CharitCasesApi extends runtime.BaseAPI implements CharitCasesApiInterface {

    /**
     * Returns a read-only Charité case by ID
     * Get a Charité case
     */
    async chariteCasesCCaseIdGetRaw(requestParameters: ChariteCasesCCaseIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChariteCase>> {
        if (requestParameters['cCaseId'] == null) {
            throw new runtime.RequiredError(
                'cCaseId',
                'Required parameter "cCaseId" was null or undefined when calling chariteCasesCCaseIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/charite/cases/{cCaseId}`;
        urlPath = urlPath.replace(`{${"cCaseId"}}`, encodeURIComponent(String(requestParameters['cCaseId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChariteCaseFromJSON(jsonValue));
    }

    /**
     * Returns a read-only Charité case by ID
     * Get a Charité case
     */
    async chariteCasesCCaseIdGet(requestParameters: ChariteCasesCCaseIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChariteCase> {
        const response = await this.chariteCasesCCaseIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
