/* tslint:disable */
/* eslint-disable */
/**
 * Patient & Case API
 * Endpoints for fetching read-only Hospital cases and managing internal patients/cases.  ## Frontend Flow 1. Enter a Hospital case ID (hospitalCaseId) 2. Fetch and display the external Hospital case 3. User clicks \"Create Case\" to create an internal case 4. Show that patient/case was created and store the caseId 5. Display the case token as QR code for scanning in the Hospital app  ## Existing Patient Access 1. Fetch all internal patients/cases 2. User selects a patient/case to view details 3. Display case details and show case token as QR code  ## App Flow 1. Receive a caseToken scanned from Hospital app 2. Fetch the internal case using POST /cases/verify-token 3. Display case details 4. Allow user to proceed with further actions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HospitalCase,
} from '../models/index';
import {
    HospitalCaseFromJSON,
    HospitalCaseToJSON,
} from '../models/index';

export interface HospitalCasesHospitalCaseIdGetRequest {
    hospitalCaseId: string;
}

/**
 * HospitalCasesApi - interface
 * 
 * @export
 * @interface HospitalCasesApiInterface
 */
export interface HospitalCasesApiInterface {
    /**
     * Returns a read-only Hospital case by ID
     * @summary Get a Hospital case
     * @param {string} hospitalCaseId Hospital case identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HospitalCasesApiInterface
     */
    hospitalCasesHospitalCaseIdGetRaw(requestParameters: HospitalCasesHospitalCaseIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HospitalCase>>;

    /**
     * Returns a read-only Hospital case by ID
     * Get a Hospital case
     */
    hospitalCasesHospitalCaseIdGet(requestParameters: HospitalCasesHospitalCaseIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HospitalCase>;

}

/**
 * 
 */
export class HospitalCasesApi extends runtime.BaseAPI implements HospitalCasesApiInterface {

    /**
     * Returns a read-only Hospital case by ID
     * Get a Hospital case
     */
    async hospitalCasesHospitalCaseIdGetRaw(requestParameters: HospitalCasesHospitalCaseIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HospitalCase>> {
        if (requestParameters['hospitalCaseId'] == null) {
            throw new runtime.RequiredError(
                'hospitalCaseId',
                'Required parameter "hospitalCaseId" was null or undefined when calling hospitalCasesHospitalCaseIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/hospital/cases/{hospitalCaseId}`;
        urlPath = urlPath.replace(`{${"hospitalCaseId"}}`, encodeURIComponent(String(requestParameters['hospitalCaseId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HospitalCaseFromJSON(jsonValue));
    }

    /**
     * Returns a read-only Hospital case by ID
     * Get a Hospital case
     */
    async hospitalCasesHospitalCaseIdGet(requestParameters: HospitalCasesHospitalCaseIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HospitalCase> {
        const response = await this.hospitalCasesHospitalCaseIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
