{{- if not .Values.enableDualRole }}
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: {{ .Values.controllerName }}
  labels:
    strimzi.io/cluster: {{ .Release.Name }}
spec:
  replicas: {{ .Values.kafkaNodePools.replicas }}
  roles:
   - controller 
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: {{ .Values.kafkaNodePools.volume.size }}
        deleteClaim: false
        kraftMetadata: shared
{{- end }}