{{- if .Values.enableDualRole }}
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: dual-role
  labels:
    strimzi.io/cluster: {{ .Release.Name }}
spec:
  replicas: {{ .Values.kafkaNodePools.replicas }}
  roles:
   - controller 
   - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: {{ .Values.kafkaNodePools.volume.size }}
        deleteClaim: false
        kraftMetadata: shared
  resources: 
    requests:
      memory: {{ .Values.dualRole.resources.requests.memory }}
      cpu: {{ .Values.dualRole.resources.requests.cpu }}
    limits:
      memory: {{ .Values.dualRole.resources.limits.memory }}
      cpu: {{ .Values.dualRole.resources.limits.cpu }}
{{- end }}