apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: {{ .Release.Name }}
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: {{ .Values.version }}
  replicas: {{ .Values.kafkaConnect.replicas}}
  bootstrapServers: {{ .Release.Name }}-kafka-bootstrap:9092
  image: "{{ .Values.kafkaConnect.image }}:{{ .Values.kafkaConnect.tag }}"
  resources:
    requests:
      memory: {{ .Values.kafkaConnect.resources.requests.memory }}
      cpu: {{ .Values.kafkaConnect.resources.requests.cpu }}
    limits:
      memory: {{ .Values.kafkaConnect.resources.limits.memory }}
      cpu: {{ .Values.kafkaConnect.resources.limits.cpu }}
  groupId: {{ .Values.kafkaConnect.group.id }}
  offsetStorageTopic: "{{ .Values.kafkaConnect.group.id }}-offsets"
  configStorageTopic: "{{ .Values.kafkaConnect.group.id }}-configs"
  statusStorageTopic: "{{ .Values.kafkaConnect.group.id }}-status"
  config:
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  jvmOptions:
    "-Xmx": "2G"
    "-Xms": "512M"