{{- $configMapName := default (printf "%s-config" .Release.Name) .Values.configMap.name -}}
{{- $secretName := default (printf "%s-secrets" .Release.Name) .Values.secret.name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ $configMapName }}
            {{- if .Values.secret.enabled }}
            - secretRef:
                name: {{ $secretName }}
            {{- end }}
