/* tslint:disable */
/* eslint-disable */
/**
 * Patient & Case API
 * Endpoints for fetching read-only Hospital cases and managing internal patients/cases.  ## Frontend Flow 1. Enter a Hospital case ID (hospitalCaseId) 2. Fetch and display the external Hospital case 3. User clicks \"Create Case\" to create an internal case 4. Show that patient/case was created and store the caseId 5. Display the case token as QR code for scanning in the Hospital app  ## Existing Patient Access 1. Fetch all internal patients/cases 2. User selects a patient/case to view details 3. Display case details and show case token as QR code  ## App Flow 1. Receive a caseToken scanned from Hospital app 2. Fetch the internal case using POST /cases/verify-token 3. Display case details 4. Allow user to proceed with further actions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CaseCreated
 */
export interface CaseCreated {
    /**
     * Internal patient identifier
     * @type {string}
     * @memberof CaseCreated
     */
    patientId: string;
    /**
     * Internal case identifier
     * @type {string}
     * @memberof CaseCreated
     */
    caseId: string;
    /**
     * JWT token for case access
     * @type {string}
     * @memberof CaseCreated
     */
    caseToken: string;
}

/**
 * Check if a given object implements the CaseCreated interface.
 */
export function instanceOfCaseCreated(value: object): value is CaseCreated {
    if (!('patientId' in value) || value['patientId'] === undefined) return false;
    if (!('caseId' in value) || value['caseId'] === undefined) return false;
    if (!('caseToken' in value) || value['caseToken'] === undefined) return false;
    return true;
}

export function CaseCreatedFromJSON(json: any): CaseCreated {
    return CaseCreatedFromJSONTyped(json, false);
}

export function CaseCreatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): CaseCreated {
    if (json == null) {
        return json;
    }
    return {
        
        'patientId': json['patientId'],
        'caseId': json['caseId'],
        'caseToken': json['caseToken'],
    };
}

export function CaseCreatedToJSON(json: any): CaseCreated {
    return CaseCreatedToJSONTyped(json, false);
}

export function CaseCreatedToJSONTyped(value?: CaseCreated | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'patientId': value['patientId'],
        'caseId': value['caseId'],
        'caseToken': value['caseToken'],
    };
}

