/* tslint:disable */
/* eslint-disable */
/**
 * Patient & Case API
 * Endpoints for fetching read-only Hospital cases and managing internal patients/cases.  ## Frontend Flow 1. Enter a Hospital case ID (hospitalCaseId) 2. Fetch and display the external Hospital case 3. User clicks \"Create Case\" to create an internal case 4. Show that patient/case was created and store the caseId 5. Display the case token as QR code for scanning in the Hospital app  ## Existing Patient Access 1. Fetch all internal patients/cases 2. User selects a patient/case to view details 3. Display case details and show case token as QR code  ## App Flow 1. Receive a caseToken scanned from Hospital app 2. Fetch the internal case using POST /cases/verify-token 3. Display case details 4. Allow user to proceed with further actions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CaseVerified
 */
export interface CaseVerified {
    /**
     * Internal case identifier
     * @type {string}
     * @memberof CaseVerified
     */
    caseId: string;
    /**
     * Patient verification string built from first letter of first name, birthdate (DDMM), and first letter of last name.
     * @type {string}
     * @memberof CaseVerified
     */
    patientVerifier: string;
    /**
     * Case status
     * @type {string}
     * @memberof CaseVerified
     */
    status: CaseVerifiedStatusEnum;
}


/**
 * @export
 */
export const CaseVerifiedStatusEnum = {
    active: 'active',
    inactive: 'inactive'
} as const;
export type CaseVerifiedStatusEnum = typeof CaseVerifiedStatusEnum[keyof typeof CaseVerifiedStatusEnum];


/**
 * Check if a given object implements the CaseVerified interface.
 */
export function instanceOfCaseVerified(value: object): value is CaseVerified {
    if (!('caseId' in value) || value['caseId'] === undefined) return false;
    if (!('patientVerifier' in value) || value['patientVerifier'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function CaseVerifiedFromJSON(json: any): CaseVerified {
    return CaseVerifiedFromJSONTyped(json, false);
}

export function CaseVerifiedFromJSONTyped(json: any, ignoreDiscriminator: boolean): CaseVerified {
    if (json == null) {
        return json;
    }
    return {
        
        'caseId': json['caseId'],
        'patientVerifier': json['patientVerifier'],
        'status': json['status'],
    };
}

export function CaseVerifiedToJSON(json: any): CaseVerified {
    return CaseVerifiedToJSONTyped(json, false);
}

export function CaseVerifiedToJSONTyped(value?: CaseVerified | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'caseId': value['caseId'],
        'patientVerifier': value['patientVerifier'],
        'status': value['status'],
    };
}

