/* tslint:disable */
/* eslint-disable */
/**
 * Patient & Case API
 * Endpoints for fetching read-only Hospital cases and managing internal patients/cases.  ## Frontend Flow 1. Enter a Hospital case ID (hospitalCaseId) 2. Fetch and display the external Hospital case 3. User clicks \"Create Case\" to create an internal case 4. Show that patient/case was created and store the caseId 5. Display the case token as QR code for scanning in the Hospital app  ## Existing Patient Access 1. Fetch all internal patients/cases 2. User selects a patient/case to view details 3. Display case details and show case token as QR code  ## App Flow 1. Receive a caseToken scanned from Hospital app 2. Fetch the internal case using POST /cases/verify-token 3. Display case details 4. Allow user to proceed with further actions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HospitalCase
 */
export interface HospitalCase {
    /**
     * Hospital case identifier
     * @type {string}
     * @memberof HospitalCase
     */
    hospitalCaseId: string;
    /**
     * Patient first name
     * @type {string}
     * @memberof HospitalCase
     */
    firstName: string;
    /**
     * Patient last name
     * @type {string}
     * @memberof HospitalCase
     */
    lastName: string;
    /**
     * Patient date of birth
     * @type {Date}
     * @memberof HospitalCase
     */
    birthDate: Date;
}

/**
 * Check if a given object implements the HospitalCase interface.
 */
export function instanceOfHospitalCase(value: object): value is HospitalCase {
    if (!('hospitalCaseId' in value) || value['hospitalCaseId'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('birthDate' in value) || value['birthDate'] === undefined) return false;
    return true;
}

export function HospitalCaseFromJSON(json: any): HospitalCase {
    return HospitalCaseFromJSONTyped(json, false);
}

export function HospitalCaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HospitalCase {
    if (json == null) {
        return json;
    }
    return {
        
        'hospitalCaseId': json['hospitalCaseId'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'birthDate': (new Date(json['birthDate'])),
    };
}

export function HospitalCaseToJSON(json: any): HospitalCase {
    return HospitalCaseToJSONTyped(json, false);
}

export function HospitalCaseToJSONTyped(value?: HospitalCase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hospitalCaseId': value['hospitalCaseId'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'birthDate': ((value['birthDate']).toISOString().substring(0,10)),
    };
}

