apiVersion: v1
kind: Secret
metadata:
  name: postgres-setup-secrets
  namespace: prod-postgres
type: Opaque
stringData:
  # The password for the 'postgres' superuser
  PGPASSWORD: "Xk9mPqL2vNwR7sYhT4jB6cAeF8gU3iZo"
  # New user passwords
  LAKEFS_PASS: "ji5VGo7BeAY3DBWa$Yjb"
  SEAWEEDFS_PASS: "tuSfWf@3UNNhw2@b9Ygq"