apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: postgres-init-wf-
  namespace: prod-postgres
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  workflowTemplateRef:
    name: postgres-init-wt