apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-pipeline-argo

resources:
  - namespace.yaml
  - https://github.com/argoproj/argo-workflows/releases/download/v3.5.0/install.yaml

patches:
  - path: server-patch.yaml