apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  SESSION_JWT_SECRET: {{ .Values.session.jwtSecret | quote }}
  {{- if .Values.grafana.jwtPrivateKey }}
  GRAFANA_JWT_PRIVATE_KEY: {{ .Values.grafana.jwtPrivateKey | quote }}
  {{- end }}
