apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: seaweedfs-init-run
  namespace: ml-pipeline-seaweedfs
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  workflowTemplateRef:
    name: seaweedfs-init-template

  ttlStrategy:
    secondsAfterCompletion: 60