deployment:
  image: 
    repository: traefik
    tag: v3.0
  args:
    - "--providers.kubernetesingress=true"
    - "--providers.kubernetescrd=true"

    - "--entrypoints.web.address=:80"
    - "--entrypoints.websecure.address=:443"

    # Enables us to use middleware etc. across namespaces to avoid resource duplication
    - "--providers.kubernetescrd.allowCrossNamespace=true"
    - "--api.dashboard=true"
    - "--log.level=TRACE"
  ports:
    - name: web
      containerPort: 80
    - name: websecure
      containerPort: 443
    - name: admin
      containerPort: 8080


service:
  type: LoadBalancer
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 80
  - name: websecure
    protocol: TCP
    port: 443
    targetPort: 443
  - name: admin
    protocol: TCP
    port: 8080
    targetPort: 8080

  annotations: {}
  lbNetworkId: ""
  lbSubnetId: ""
  workerNodeSubnetId: ""
  lbIP: ""

clusterIssuer:
  enabled: false
  name: letsencrypt-prod
  acmeServer: https://acme-v02.api.letsencrypt.org/directory
  email: ""
  privateKeySecretName: letsencrypt-prod
  ingressClass: traefik

    

