{
 "title": "Kafka Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Messages total per topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesinpersec_total{topic=~\"dlq|wearables-lp|wearables-raw\"}",
     "legendFormat": "{{topic}}-{{instance}}"
    }
   ]
  },
  {
   "title": "MB in topic total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_server_brokertopicmetrics_bytesinpersec_total{topic=~\"dlq|wearables-lp|wearables-raw\"}) / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total partitions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globalpartitioncount{job=\"kafka-metrics-reporter\"})",
     "legendFormat": "total partitions"
    }
   ]
  },
  {
   "title": "Replication by topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max by(topic) (kafka_cluster_partition_replicascount{topic=~\"wearables-raw|dlq|wearables-lp\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topic Count",
   "type": "stat",
   "description": "Topic Count /wo replication",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount{job=\"kafka-metrics-reporter\"}) / 3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Broker Count",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activebrokercount{instance=\"172.25.1.12:9404\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}