ingress:
  host: "wearable-analytics.de"

serversTransport:
  forwardingTimeouts:
    dialTimeout: 60s
    responseHeaderTimeout: 60s
    idleConnTimeout: 60s

certificate:
  name: wearables-cert
  secretName: wearables-tls
