apiVersion: v2
name: seaweedfs-wrapper
description: A SeaweedFS Helm chart for Kubernetes
version: 2.0.0

# Umbrella Chart pattern: This chart depends on the official SeaweedFS chart as a sub-chart
# https://github.com/seaweedfs/seaweedfs/tree/master/k8s/charts/seaweedfs
# it tells Helm to download the official SeaweedFS chart and put it inside deployment
dependencies:
  - name: seaweedfs
    version: "3.59" 
    repository: https://seaweedfs.github.io/seaweedfs/helm
