apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  annotations:
    loadbalancer.openstack.org/network-id: {{ .Values.service.lbNetworkId }}
    loadbalancer.openstack.org/subnet-id: {{ .Values.service.lbSubnetId }}
    loadbalancer.openstack.org/member-subnet-id: {{ .Values.service.workerNodeSubnetId }}
spec:
  type: LoadBalancer
  # public IPv4 from openstack
  loadBalancerIP: {{ .Values.service.lbIP }}
  selector:
    app: {{ .Release.Name }}
  ports:
  {{- range .Values.service.ports }}
  - name: {{ .name }}
    protocol: {{ .protocol }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
  {{- end }}