replicas: 1

mapperEnvConfigMap: mapper-app-env-config
mappingConfig: mapping-config
mappingConfigVol: mapping-config-vol

envs:
  brokerEnv: "kafka-kafka-bootstrap:9092"
  appId: "mapper-validator"
  fhirMappingYamlPath:  "/config/mapping.yaml"
  inputTopic: "wearables-raw"
  outputTopic: "wearables-lp"
  dlqTopic: "dlq"

image:
  repository: lndocker3s/mapper-validator
  tag: 0.1.1
  imagePullPolicy: Always
