replicas: 3

mapperEnvConfigMap: mapper-app-env-config
mappingConfig: mapping-config
mappingConfigVol: mapping-config-vol

envs:
  brokerEnv: "kafka-kafka-bootstrap:9092"
  appId: "mapper-validator"
  fhirMappingYamlPath:  "/config/mapping.yaml"
  inputTopic: "wearables-raw"
  outputTopic: "wearables-lp"
  dlqTopic: "dlq"
  numStreamThreads: "10" #how many partitions one instance can handle through multithreading
  partitions: "30" #number of partitions that the wearables raw topic has
  validationFrequency: 100 # every n-th message will be checked according to this (if 0, all messages are checked)


image:
  repository: lndocker3s/mapper-validator
  tag: 0.2.1
  imagePullPolicy: Always
