replicas: 3

mapperEnvConfigMap: mapper-app-env-config
mappingConfig: mapping-config
mappingConfigVol: mapping-config-vol

envs:
  brokerEnv: "kafka-kafka-bootstrap:9092"
  appId: "mapper-validator"
  fhirMappingYamlPath:  "/config/mapping.yaml"
  inputTopic: "wearables-raw"
  outputTopic: "wearables-lp"
  dlqTopic: "dlq"
  numStreamThreads: "10" #how many partitions one instance can handle through multithreading
  partitions: "30" #number of partitions that the wearables raw topic has


image:
  repository: wearables42/mapper-validator
  tag: 0.3.1
  imagePullPolicy: Always
