apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  ENCRYPTION_KEY: {{ .Values.infisical.encryptionKey }}
  JWT_AUTH_SECRET: {{ .Values.infisical.jwtAuthSecret }}
  JWT_REFRESH_SECRET: {{ .Values.infisical.jwtRefreshSecret }}
  JWT_SERVICE_SECRET: {{ .Values.infisical.jwtServiceSecret }}
  DB_CONNECTION_URI: "postgresql://{{ .Values.externalPostgres.username }}:{{ .Values.externalPostgres.password }}@{{ .Values.externalPostgres.host }}:{{ .Values.externalPostgres.port }}/{{ .Values.externalPostgres.database }}"
