{{- $configMapName := default (printf "%s-config" .Release.Name) .Values.configMap.name -}}
{{- $secretName := default (printf "%s-secrets" .Release.Name) .Values.secret.name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.proxy.port }}
              name: http
          envFrom:
            - configMapRef:
                name: {{ $configMapName }}
            - secretRef:
                name: {{ $secretName }}
          volumeMounts:
            - name: grafana-jwt-key
              mountPath: /secrets/grafana-jwt-private.pem
              subPath: grafana-jwt-private.pem
              readOnly: true
      volumes:
        - name: grafana-jwt-key
          secret:
            secretName: {{ $secretName }}
            items:
              - key: GRAFANA_JWT_PRIVATE_KEY
                path: grafana-jwt-private.pem
