{{- if and .Values.ingress.enabled (not .Values.ingress.httpOnly) }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ .Release.Name }}-https"
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`{{ .Values.ingress.host }}`) && PathPrefix(`{{ .Values.ingress.pathPrefix }}`)"
      kind: Rule
      services:
        - name: {{ .Release.Name }}
          port: 80
  tls:
    secretName: {{ .Values.ingress.certificateSecretName }}
{{- end }}
