{{- $secretName := default (printf "%s-secrets" .Release.Name) .Values.secret.name -}}
{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
