apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  APP_JWT_SECRET: {{ .Values.session.jwtSecret | quote }}
  GRAFANA_JWT_PRIVATE_KEY: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCX8BlZIrdzgO4a
    ff2/BNc4oOMOwm33FPSlkKqqP6xRWzYnm52ipQcyCjxLdyXBlehN+X+ZCiajUcNM
    RGmV8v8mOwpZlyuctt0gyTfYL0CXyTdsA9Jg3ZzxFwO644ET4ocgdBOgPRacKX5h
    ey+pEg1BLbtBlLzbEfP2wt0uqLLKAo0F7KYcwFmP+xlIKZOOjWG0AT0IHe3s1Rz4
    IncYkAgJZKeHUE009DSJFazJKhYZdUYLgE18hEZtNQ0fU2JvIdf2BLf0KnLmBSmX
    tI2plUoqOSshOFCFxdQnPWY1bVVTZ2yljCQjevvghq3xpKxl1y2UkVv0qhuKYXaN
    9BfcAspzAgMBAAECggEAIKtIEAHmdyfsSnb3tfho/Gyflb9ZnKx9VBIwmA270/xs
    PwT3Vo7sZqaLw2A5lo/QlN+GP5ZOq4Q7nW0CVPMcSJCeT5gxEO/CyTdq0gmK9ngV
    +hwyQpC0G6SqsScUzH1DN8etpqEr+OT1Hym5HD3c6rxWDKpaFzKbhd3taAhu9P9V
    aI1yP7shUdv8+/sgaeyArlPz1Pu4H6ZgQ73/g+qX9b91zCle2zfjATZwOkeHvfOl
    G5EgRSFFZYljcxRs6KMGdhdtx4Nx/vx+N0IQ4bvf2QKJ+WNcupDP+3/l9D3isVtC
    zXsiECGMQkMGRslpq8kOnN8qy58j3u6/Q1VKoMWj7QKBgQDTBjPAxOkXya4kA5GK
    NkvESgHXGEiM5IO8BZPAqRG9mO6osE25RbouiA0OSYTZWb/ZCelqGh7z0haFNS71
    uo/PmwUdazhBY7ihV/AqrQgbJZGQQWnY/3810N0KlUx8Kx0IESAdnVxeyjmVEPMh
    qhp1JmO9wnbw6Qn5VUdNYLXADQKBgQC4Ug7BskBC2xGnocUzl1VllwpN93jHraWA
    oOkIwGzcn27fiTT5BeUGcoPGMIO1siPX+DOwvT+ERyfHNX36nZclFZyWPVAW2aVf
    yWLPLK4la0XgQVkWgUwfSkCKDslLL+dFXVBIoPWTj96T4XP+MvaC7g8/sf8lQGHn
    g9JaFNWUfwKBgHQnAMuFVyvRxflqwWxLEI89kR+87QooKd6PT1GHfg1XJV5SlKV7
    HMzJ9C2+B9K/FNs5GnJdaFYaeGzf5jY5dzj1ge48ex1670BXsAk9bq3KkwHND57y
    mymbCl/t58iczoEHNB8444QFWYaUas9H2wJKnDHx3RgjnWrRJssPhVrtAoGAV497
    vR5NkrT4/RZHVQvWII2Q8prWQJ1IGwPV0DeBP4lppT1L8eSP+PEbkmHnn8ABcQ5S
    l+o/KzqWNfc+YnjMnWxX17NGwaQhAJDtpJeIHvSH3FGO3bcMj2y5nhwKGfKmvffn
    NKlqH/BffwbCEIbrPiWTDuIi3/Jm0BF6Mxrkn0cCgYA55NniPzndcyjqCcVHtMhw
    Lm1Y+n01Za6Uzh6v9dUD9cg+9097nRBlucwK10ZBKw9TiJfZEZ1Z1iRVYJqpQKNR
    vlImhRK3+CfWi7Q8ZkBzA7aRrxg5VKoST2OK1p7rOR2kHVH5zXZEZmm3J0VllzcZ
    TmwC4UHycVbT2f3vtTpKXw==
    -----END PRIVATE KEY-----
