apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
            - name: API_PREFIX
              value: {{ .Values.env.API_PREFIX | quote }}
            - name: USE_MOCK_DATA
              value: {{ .Values.env.USE_MOCK_DATA | quote }}
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
          envFrom:
            - secretRef:
                name: {{ .Values.secretRef }}
