apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretRef }}
type: Opaque
stringData:
  # Replace the following with your actual secrets
  DATABASE_API_URL: "http://db-lord.db-lord.svc.cluster.local:8080"
  JWT_SECRET: "dev-secret"
