apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretRef }}
type: Opaque
stringData:
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "admin-password"
  POSTGRES_DB: "db"

  DATABASE_URL: "postgresql+psycopg2://admin:admin-password@postgres.postgres.svc.cluster.local:5432/db"
  CHARITE_URL: "http://localhost:9090"
  SECRET_KEY: "secret"
  TOKEN_EXPIRATION: "900"

  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SENDER_EMAIL: "test.dsp.wearables@gmail.com"
  APP_PASSWORD: "dbtj jtvi enli ehdj"

  JWT_SECRET: "secret"
  JWT_ALGORITHM: "HS256"