all:
  hosts:
    k3s_server:
      ansible_host: 94.130.230.161
      ansible_user: rknntns
      ansible_become: yes
      ansible_become_method: sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3
