[project]
name = "db-lord"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiocsv>=1.4.0",
    "aiohttp>=3.13.2",
    "alembic[tz]>=1.17.2",
    "asyncpg>=0.31.0",
    "fastapi>=0.128.0",
    "greenlet>=3.3.0",
    "influxdb-client>=1.49.0",
    "pydantic-settings>=2.12.0",
    "python-dateutil>=2.9.0.post0",
    "requests>=2.32.5",
    "sqlalchemy>=2.0.45",
    "uvicorn[standard]>=0.40.0",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "ruff>=0.14.10",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
# E/F = Standard, I = Imports
# B = Find Bugs, UP = Modernize Syntax, SIM = Simplify Code
select = ["E", "F", "I", "B", "UP", "SIM"]
fixable = ["ALL"]

