/* tslint:disable */
/* eslint-disable */
/**
 * Patient & Case API
 * Endpoints for fetching read-only Charité cases and managing internal patients/cases.  ## Frontend Flow 1. Enter a Charité case ID (cCaseId) 2. Fetch and display the external Charité case 3. User clicks \"Create Case\" to create an internal case 4. Show that patient/case was created and store the caseId 5. Display the case token as QR code for scanning in the Charité app  ## Existing Patient Access 1. Fetch all internal patients/cases 2. User selects a patient/case to view details 3. Display case details and show case token as QR code  ## App Flow 1. Receive a caseToken scanned from Charité app 2. Fetch the internal case using POST /cases/verify-token 3. Display case details 4. Allow user to proceed with further actions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CasesFromChariteCasePostRequest
 */
export interface CasesFromChariteCasePostRequest {
    /**
     * Charité case identifier
     * @type {string}
     * @memberof CasesFromChariteCasePostRequest
     */
    cCaseId: string;
}

/**
 * Check if a given object implements the CasesFromChariteCasePostRequest interface.
 */
export function instanceOfCasesFromChariteCasePostRequest(value: object): value is CasesFromChariteCasePostRequest {
    if (!('cCaseId' in value) || value['cCaseId'] === undefined) return false;
    return true;
}

export function CasesFromChariteCasePostRequestFromJSON(json: any): CasesFromChariteCasePostRequest {
    return CasesFromChariteCasePostRequestFromJSONTyped(json, false);
}

export function CasesFromChariteCasePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CasesFromChariteCasePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'cCaseId': json['cCaseId'],
    };
}

export function CasesFromChariteCasePostRequestToJSON(json: any): CasesFromChariteCasePostRequest {
    return CasesFromChariteCasePostRequestToJSONTyped(json, false);
}

export function CasesFromChariteCasePostRequestToJSONTyped(value?: CasesFromChariteCasePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cCaseId': value['cCaseId'],
    };
}

