/* tslint:disable */
/* eslint-disable */
/**
 * Patient & Case API
 * Endpoints for fetching read-only Charité cases and managing internal patients/cases.  ## Frontend Flow 1. Enter a Charité case ID (cCaseId) 2. Fetch and display the external Charité case 3. User clicks \"Create Case\" to create an internal case 4. Show that patient/case was created and store the caseId 5. Display the case token as QR code for scanning in the Charité app  ## Existing Patient Access 1. Fetch all internal patients/cases 2. User selects a patient/case to view details 3. Display case details and show case token as QR code  ## App Flow 1. Receive a caseToken scanned from Charité app 2. Fetch the internal case using POST /cases/verify-token 3. Display case details 4. Allow user to proceed with further actions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChariteCase
 */
export interface ChariteCase {
    /**
     * Charité case identifier
     * @type {string}
     * @memberof ChariteCase
     */
    cCaseId: string;
    /**
     * Patient first name
     * @type {string}
     * @memberof ChariteCase
     */
    firstName: string;
    /**
     * Patient last name
     * @type {string}
     * @memberof ChariteCase
     */
    lastName: string;
    /**
     * Patient date of birth
     * @type {Date}
     * @memberof ChariteCase
     */
    birthDate: Date;
}

/**
 * Check if a given object implements the ChariteCase interface.
 */
export function instanceOfChariteCase(value: object): value is ChariteCase {
    if (!('cCaseId' in value) || value['cCaseId'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('birthDate' in value) || value['birthDate'] === undefined) return false;
    return true;
}

export function ChariteCaseFromJSON(json: any): ChariteCase {
    return ChariteCaseFromJSONTyped(json, false);
}

export function ChariteCaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChariteCase {
    if (json == null) {
        return json;
    }
    return {
        
        'cCaseId': json['cCaseId'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'birthDate': (new Date(json['birthDate'])),
    };
}

export function ChariteCaseToJSON(json: any): ChariteCase {
    return ChariteCaseToJSONTyped(json, false);
}

export function ChariteCaseToJSONTyped(value?: ChariteCase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cCaseId': value['cCaseId'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'birthDate': ((value['birthDate']).toISOString().substring(0,10)),
    };
}

