apiVersion: cluster.k8s.io/v1alpha1
kind: MachineDeployment
metadata:
  annotations:
    k8c.io/operating-system-profile: osp-ubuntu
  name: wearables-node
  namespace: kube-system
spec:
  replicas: 3
  selector:
    matchLabels:
      machine: md-${KKP_CLUSTER_ID}-wrl8vhwxjr
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        machine: md-${KKP_CLUSTER_ID}-wrl8vhwxjr
    spec:
      metadata:
        labels:
          machine: md-${KKP_CLUSTER_ID}-wrl8vhwxjr
          system/cluster: ${KKP_CLUSTER_ID}
          system/project: ${KKP_PROJECT_ID}
      providerSpec:
        value:
          caPublicKey: ""
          cloudProvider: openstack
          cloudProviderSpec:
            applicationCredentialID: ""
            applicationCredentialSecret: ""
            availabilityZone: nova
            computeAPIVersion: ""
            configDrive: false
            domainName: ""
            flavor: de.NBI k8c
            floatingIpPool: public
            identityEndpoint: https://denbi-cloud.bihealth.org:13000/v3
            image: Ubuntu-24.04
            instanceReadyCheckPeriod: 5s
            instanceReadyCheckTimeout: 120s
            network: kubernetes-${KKP_CLUSTER_ID}
            password: ""
            projectID: ""
            projectName: ""
            region: regionOne
            rootDiskVolumeType: ""
            securityGroups:
            - kubernetes-${KKP_CLUSTER_ID}
            serverGroup: ""
            subnet: ${OS_SUBNET_ID}
            tags:
              kubernetes-cluster: ${KKP_CLUSTER_ID}
              system-cluster: ${KKP_CLUSTER_ID}
              system-project: ${KKP_PROJECT_ID}
            tenantID: ""
            tenantName: ""
            tokenId: ""
            trustDevicePath: false
            username: ""
          network:
            cidr: ""
            gateway: ""
            ipFamily: IPv4
          operatingSystem: ubuntu
          operatingSystemSpec:
            distUpgradeOnBoot: false
          sshPublicKeys: ${SSH_PUBLIC_KEYS_JSON}
      versions:
        kubelet: 1.31.13
