"""switched_to_ORM

Revision ID: afb10388d1d0
Revises: cf15102f167f
Create Date: 2026-02-09 10:53:51.109168+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "afb10388d1d0"
down_revision: str | Sequence[str] | None = "cf15102f167f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    case_status_enum = sa.Enum("PLANNED", "ONGOING", "COMPLETED", "ARCHIVED", "OTHER", name="case_status_enum")
    hardware_status_enum = sa.Enum(
        "AVAILABLE",
        "ASSIGNED",
        "BROKEN",
        "IN_REPAIR",
        "IN_MAINTENANCE",
        "DECOMMISSIONED",
        "LOST",
        "OTHER",
        name="hardware_status_enum",
    )
    case_status_enum.create(op.get_bind(), checkfirst=True)
    hardware_status_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "export_jobs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "status", sa.Enum("PENDING", "RUNNING", "COMPLETE", "FAILED", name="export_job_status_enum"), nullable=False
        ),
        sa.Column("requested_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("error", sa.String(length=2048), nullable=True),
        sa.Column("result_path", sa.String(length=2048), nullable=True),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_export_jobs")),
    )
    op.create_index(op.f("ix_export_jobs_status"), "export_jobs", ["status"], unique=False)
    op.create_table(
        "fhir_mappings",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("version", sa.String(length=128), nullable=False),
        sa.Column("full_mapping", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fhir_mappings")),
    )
    op.create_index(op.f("ix_fhir_mappings_version"), "fhir_mappings", ["version"], unique=True)
    op.create_table(
        "fhir_mapping_trees",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("version", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=128), nullable=False),
        sa.Column("map_tree", sa.JSON(), nullable=False),
        sa.Column("mapping_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mapping_id"],
            ["fhir_mappings.id"],
            name=op.f("fk_fhir_mapping_trees_mapping_id_fhir_mappings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fhir_mapping_trees")),
    )
    op.create_index(
        "ix_fhir_mapping_tree_version_category", "fhir_mapping_trees", ["version", "category"], unique=False
    )
    op.create_index(op.f("ix_fhir_mapping_trees_category"), "fhir_mapping_trees", ["category"], unique=False)
    op.drop_table("map_trees")
    op.drop_table("mappings")
    op.create_index(op.f("ix_case_contexts_context_id"), "case_contexts", ["context_id"], unique=False)
    op.create_index(
        "ix_case_devices_active_by_device",
        "case_devices",
        ["device_id"],
        unique=False,
        postgresql_where=sa.text("assigned_to IS NULL"),
    )
    op.create_index(
        "ix_case_wearables_active_by_wearable",
        "case_wearables",
        ["wearable_id"],
        unique=False,
        postgresql_where=sa.text("assigned_to IS NULL"),
    )
    op.create_check_constraint(
        "ck_case_devices_assigned_order",
        "case_devices",
        "assigned_to IS NULL OR assigned_to > assigned_from",
    )
    op.create_check_constraint(
        "ck_case_wearables_assigned_order",
        "case_wearables",
        "assigned_to IS NULL OR assigned_to > assigned_from",
    )
    op.execute(
        "ALTER TABLE case_devices "
        "ADD CONSTRAINT ex_case_device_no_overlap "
        "EXCLUDE USING gist "
        "(device_id WITH =, tstzrange(assigned_from, COALESCE(assigned_to, 'infinity'::timestamptz), '[)') WITH &&)"
    )
    op.execute(
        "ALTER TABLE case_wearables "
        "ADD CONSTRAINT ex_case_wearable_no_overlap "
        "EXCLUDE USING gist "
        "(wearable_id WITH =, tstzrange(assigned_from, COALESCE(assigned_to, 'infinity'::timestamptz), '[)') WITH &&)"
    )
    op.execute("ALTER TABLE cases ALTER COLUMN status DROP DEFAULT")
    op.alter_column(
        "cases",
        "status",
        existing_type=postgresql.ENUM("PLANNED", "ONGOING", "COMPLETED", "ARCHIVED", "OTHER", name="case_status"),
        type_=sa.Enum("PLANNED", "ONGOING", "COMPLETED", "ARCHIVED", "OTHER", name="case_status_enum"),
        postgresql_using="status::text::case_status_enum",
        existing_nullable=False,
    )
    op.execute("ALTER TABLE cases ALTER COLUMN status SET DEFAULT 'PLANNED'::case_status_enum")
    op.drop_index(op.f("ix_cases_patient_id"), table_name="cases")
    op.create_index("ix_cases_patient_status", "cases", ["patient_id", "status"], unique=False)
    op.create_index(op.f("ix_cases_status"), "cases", ["status"], unique=False)
    op.execute("ALTER TABLE devices ALTER COLUMN status DROP DEFAULT")
    op.alter_column(
        "devices",
        "status",
        existing_type=postgresql.ENUM(
            "AVAILABLE", "ASSIGNED", "IN_REPAIR", "DECOMMISSIONED", "LOST", "OTHER", name="hardware_status"
        ),
        type_=sa.Enum(
            "AVAILABLE",
            "ASSIGNED",
            "BROKEN",
            "IN_REPAIR",
            "IN_MAINTENANCE",
            "DECOMMISSIONED",
            "LOST",
            "OTHER",
            name="hardware_status_enum",
        ),
        postgresql_using="status::text::hardware_status_enum",
        existing_nullable=False,
    )
    op.execute("ALTER TABLE devices ALTER COLUMN status SET DEFAULT 'AVAILABLE'::hardware_status_enum")
    op.create_index(
        "ix_devices_model_trgm",
        "devices",
        ["model"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"model": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_devices_status"), "devices", ["status"], unique=False)
    op.alter_column(
        "patients",
        "weight",
        existing_type=sa.NUMERIC(precision=6, scale=2),
        type_=sa.Numeric(precision=5, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "patients",
        "height",
        existing_type=sa.NUMERIC(precision=4, scale=2),
        type_=sa.Numeric(precision=5, scale=2),
        existing_nullable=True,
    )
    op.create_index(op.f("ix_patients_dob"), "patients", ["dob"], unique=False)
    op.create_index(
        "ix_patients_name_trgm",
        "patients",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_patients_sex"), "patients", ["sex"], unique=False)
    op.create_unique_constraint(op.f("uq_patients_charite_id"), "patients", ["charite_id"])
    op.execute("ALTER TABLE wearables ALTER COLUMN status DROP DEFAULT")
    op.alter_column(
        "wearables",
        "status",
        existing_type=postgresql.ENUM(
            "AVAILABLE", "ASSIGNED", "IN_REPAIR", "DECOMMISSIONED", "LOST", "OTHER", name="hardware_status"
        ),
        type_=sa.Enum(
            "AVAILABLE",
            "ASSIGNED",
            "BROKEN",
            "IN_REPAIR",
            "IN_MAINTENANCE",
            "DECOMMISSIONED",
            "LOST",
            "OTHER",
            name="hardware_status_enum",
        ),
        postgresql_using="status::text::hardware_status_enum",
        existing_nullable=False,
    )
    op.execute("ALTER TABLE wearables ALTER COLUMN status SET DEFAULT 'AVAILABLE'::hardware_status_enum")
    op.create_index(
        "ix_wearables_model_trgm",
        "wearables",
        ["model"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"model": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_wearables_status"), "wearables", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE case_wearables DROP CONSTRAINT IF EXISTS ex_case_wearable_no_overlap")
    op.execute("ALTER TABLE case_devices DROP CONSTRAINT IF EXISTS ex_case_device_no_overlap")
    op.drop_constraint("ck_case_wearables_assigned_order", "case_wearables", type_="check")
    op.drop_constraint("ck_case_devices_assigned_order", "case_devices", type_="check")

    op.drop_index(op.f("ix_wearables_status"), table_name="wearables")
    op.drop_index(
        "ix_wearables_model_trgm",
        table_name="wearables",
        postgresql_using="gin",
        postgresql_ops={"model": "gin_trgm_ops"},
    )
    op.execute("ALTER TABLE wearables ALTER COLUMN status DROP DEFAULT")
    op.alter_column(
        "wearables",
        "status",
        existing_type=sa.Enum(
            "AVAILABLE",
            "ASSIGNED",
            "BROKEN",
            "IN_REPAIR",
            "IN_MAINTENANCE",
            "DECOMMISSIONED",
            "LOST",
            "OTHER",
            name="hardware_status_enum",
        ),
        type_=postgresql.ENUM(
            "AVAILABLE", "ASSIGNED", "IN_REPAIR", "DECOMMISSIONED", "LOST", "OTHER", name="hardware_status"
        ),
        postgresql_using="status::text::hardware_status",
        existing_nullable=False,
    )
    op.execute("ALTER TABLE wearables ALTER COLUMN status SET DEFAULT 'AVAILABLE'::hardware_status")
    op.drop_constraint(op.f("uq_patients_charite_id"), "patients", type_="unique")
    op.drop_index(op.f("ix_patients_sex"), table_name="patients")
    op.drop_index(
        "ix_patients_name_trgm", table_name="patients", postgresql_using="gin", postgresql_ops={"name": "gin_trgm_ops"}
    )
    op.drop_index(op.f("ix_patients_dob"), table_name="patients")
    op.alter_column(
        "patients",
        "height",
        existing_type=sa.Numeric(precision=5, scale=2),
        type_=sa.NUMERIC(precision=4, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "patients",
        "weight",
        existing_type=sa.Numeric(precision=5, scale=2),
        type_=sa.NUMERIC(precision=6, scale=2),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_devices_status"), table_name="devices")
    op.drop_index(
        "ix_devices_model_trgm", table_name="devices", postgresql_using="gin", postgresql_ops={"model": "gin_trgm_ops"}
    )
    op.execute("ALTER TABLE devices ALTER COLUMN status DROP DEFAULT")
    op.alter_column(
        "devices",
        "status",
        existing_type=sa.Enum(
            "AVAILABLE",
            "ASSIGNED",
            "BROKEN",
            "IN_REPAIR",
            "IN_MAINTENANCE",
            "DECOMMISSIONED",
            "LOST",
            "OTHER",
            name="hardware_status_enum",
        ),
        type_=postgresql.ENUM(
            "AVAILABLE", "ASSIGNED", "IN_REPAIR", "DECOMMISSIONED", "LOST", "OTHER", name="hardware_status"
        ),
        postgresql_using="status::text::hardware_status",
        existing_nullable=False,
    )
    op.execute("ALTER TABLE devices ALTER COLUMN status SET DEFAULT 'AVAILABLE'::hardware_status")
    op.drop_index(op.f("ix_cases_status"), table_name="cases")
    op.drop_index("ix_cases_patient_status", table_name="cases")
    op.create_index(op.f("ix_cases_patient_id"), "cases", ["patient_id"], unique=False)
    op.execute("ALTER TABLE cases ALTER COLUMN status DROP DEFAULT")
    op.alter_column(
        "cases",
        "status",
        existing_type=sa.Enum("PLANNED", "ONGOING", "COMPLETED", "ARCHIVED", "OTHER", name="case_status_enum"),
        type_=postgresql.ENUM("PLANNED", "ONGOING", "COMPLETED", "ARCHIVED", "OTHER", name="case_status"),
        postgresql_using="status::text::case_status",
        existing_nullable=False,
    )
    op.execute("ALTER TABLE cases ALTER COLUMN status SET DEFAULT 'PLANNED'::case_status")
    op.drop_index(
        "ix_case_wearables_active_by_wearable",
        table_name="case_wearables",
        postgresql_where=sa.text("assigned_to IS NULL"),
    )
    op.drop_index(
        "ix_case_devices_active_by_device", table_name="case_devices", postgresql_where=sa.text("assigned_to IS NULL")
    )
    op.drop_index(op.f("ix_case_contexts_context_id"), table_name="case_contexts")
    op.create_table(
        "mappings",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), autoincrement=False, nullable=False),
        sa.Column("version", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("full_mapping", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mappings")),
    )
    op.create_table(
        "map_trees",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), autoincrement=False, nullable=False),
        sa.Column("version", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("map_tree", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("mapping_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["mapping_id"], ["mappings.id"], name=op.f("fk_map_trees_mapping_id_mappings"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_map_trees")),
    )
    op.drop_index(op.f("ix_fhir_mapping_trees_category"), table_name="fhir_mapping_trees")
    op.drop_index("ix_fhir_mapping_tree_version_category", table_name="fhir_mapping_trees")
    op.drop_table("fhir_mapping_trees")
    op.drop_index(op.f("ix_fhir_mappings_version"), table_name="fhir_mappings")
    op.drop_table("fhir_mappings")
    op.drop_index(op.f("ix_export_jobs_status"), table_name="export_jobs")
    op.drop_table("export_jobs")
    # ### end Alembic commands ###
