"""added_mappings

Revision ID: cf15102f167f
Revises: 14f5dcf69328
Create Date: 2026-02-05 13:52:49.423727+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf15102f167f"
down_revision: str | Sequence[str] | None = "14f5dcf69328"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mappings",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("full_mapping", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mappings")),
    )
    op.create_table(
        "map_trees",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("map_tree", sa.JSON(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("mapping_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mapping_id"], ["mappings.id"], name=op.f("fk_map_trees_mapping_id_mappings"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_map_trees")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("map_trees")
    op.drop_table("mappings")
    # ### end Alembic commands ###
