"""updated_names

Revision ID: 1a8bf4401c37
Revises: 3b9e6f7c9a11
Create Date: 2026-02-16 14:46:37.263615+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a8bf4401c37"
down_revision: str | Sequence[str] | None = "3b9e6f7c9a11"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dot_dependency_files",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("version", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=128), nullable=False),
        sa.Column("digraph", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("mapping_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mapping_id"],
            ["fhir_mappings.id"],
            name=op.f("fk_dot_dependency_files_mapping_id_fhir_mappings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dot_dependency_files")),
    )
    op.create_index(op.f("ix_dot_dependency_files_category"), "dot_dependency_files", ["category"], unique=False)
    op.create_index(
        "ix_dot_dependency_files_version_category", "dot_dependency_files", ["version", "category"], unique=False
    )
    op.drop_index(op.f("ix_fhir_mapping_tree_version_category"), table_name="fhir_mapping_trees")
    op.drop_index(op.f("ix_fhir_mapping_trees_category"), table_name="fhir_mapping_trees")
    op.drop_table("fhir_mapping_trees")
    op.alter_column(
        "fhir_mappings",
        "full_mapping",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fhir_mappings",
        "full_mapping",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.create_table(
        "fhir_mapping_trees",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), autoincrement=False, nullable=False),
        sa.Column("version", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column("map_tree", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("mapping_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["mapping_id"],
            ["fhir_mappings.id"],
            name=op.f("fk_fhir_mapping_trees_mapping_id_fhir_mappings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fhir_mapping_trees")),
    )
    op.create_index(op.f("ix_fhir_mapping_trees_category"), "fhir_mapping_trees", ["category"], unique=False)
    op.create_index(
        op.f("ix_fhir_mapping_tree_version_category"), "fhir_mapping_trees", ["version", "category"], unique=False
    )
    op.drop_index("ix_dot_dependency_files_version_category", table_name="dot_dependency_files")
    op.drop_index(op.f("ix_dot_dependency_files_category"), table_name="dot_dependency_files")
    op.drop_table("dot_dependency_files")
    # ### end Alembic commands ###
