"""added_indexes

Revision ID: 1a4f3c9e51fc
Revises: 1a8bf4401c37
Create Date: 2026-02-24 06:31:39.918821+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a4f3c9e51fc"
down_revision: str | Sequence[str] | None = "1a8bf4401c37"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_case_contexts_context_case_desc",
        "case_contexts",
        ["context_id", sa.literal_column("case_id DESC")],
        unique=False,
    )
    op.create_index(
        "ix_case_devices_case_assigned_from_desc",
        "case_devices",
        ["case_id", sa.literal_column("assigned_from DESC"), sa.literal_column("device_id DESC")],
        unique=False,
        postgresql_include=["assigned_to"],
    )
    op.create_index(
        "ix_case_devices_device_assigned_from_desc",
        "case_devices",
        ["device_id", sa.literal_column("assigned_from DESC"), sa.literal_column("case_id DESC")],
        unique=False,
        postgresql_include=["assigned_to"],
    )
    op.create_index(
        "ix_case_wearables_case_assigned_from_desc",
        "case_wearables",
        ["case_id", sa.literal_column("assigned_from DESC"), sa.literal_column("wearable_id DESC")],
        unique=False,
        postgresql_include=["assigned_to"],
    )
    op.create_index(
        "ix_case_wearables_wearable_assigned_from_desc",
        "case_wearables",
        ["wearable_id", sa.literal_column("assigned_from DESC"), sa.literal_column("case_id DESC")],
        unique=False,
        postgresql_include=["assigned_to"],
    )
    op.create_index("ix_cases_patient_id_id_desc", "cases", ["patient_id", sa.literal_column("id DESC")], unique=False)
    op.create_index(op.f("ix_dot_dependency_files_version"), "dot_dependency_files", ["version"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dot_dependency_files_version"), table_name="dot_dependency_files")
    op.drop_index("ix_cases_patient_id_id_desc", table_name="cases")
    op.drop_index(
        "ix_case_wearables_wearable_assigned_from_desc", table_name="case_wearables", postgresql_include=["assigned_to"]
    )
    op.drop_index(
        "ix_case_wearables_case_assigned_from_desc", table_name="case_wearables", postgresql_include=["assigned_to"]
    )
    op.drop_index(
        "ix_case_devices_device_assigned_from_desc", table_name="case_devices", postgresql_include=["assigned_to"]
    )
    op.drop_index(
        "ix_case_devices_case_assigned_from_desc", table_name="case_devices", postgresql_include=["assigned_to"]
    )
    op.drop_index("ix_case_contexts_context_case_desc", table_name="case_contexts")
    # ### end Alembic commands ###
