"""initial_schema

Revision ID: 14f5dcf69328
Revises:
Create Date: 2026-01-03 19:56:37.675020+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14f5dcf69328"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contexts",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("group_name", sa.String(), nullable=False),
        sa.Column("coordinator", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contexts")),
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("serial_nr", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("manufacturer", sa.String(), nullable=True),
        sa.Column("os_version", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("AVAILABLE", "ASSIGNED", "IN_REPAIR", "DECOMMISSIONED", "LOST", "OTHER", name="hardware_status"),
            server_default="AVAILABLE",  # And here
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("serial_nr", name=op.f("uq_devices_serial_nr")),
    )
    op.create_table(
        "patients",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("charite_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("sex", sa.String(), nullable=True),
        sa.Column("dob", sa.Date(), nullable=True),
        sa.Column("weight", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("height", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patients")),
    )
    op.create_table(
        "wearables",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("serial_nr", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("manufacturer", sa.String(), nullable=True),
        sa.Column("os_version", sa.String(), nullable=False),
        sa.Column(
            "status",
            # Use UPPERCASE strings here:
            sa.Enum("AVAILABLE", "ASSIGNED", "IN_REPAIR", "DECOMMISSIONED", "LOST", "OTHER", name="hardware_status"),
            server_default="AVAILABLE",  # And here
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wearables")),
        sa.UniqueConstraint("serial_nr", name=op.f("uq_wearables_serial_nr")),
    )
    op.create_table(
        "cases",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "status",
            # Use UPPERCASE strings here:
            sa.Enum("PLANNED", "ONGOING", "COMPLETED", "ARCHIVED", "OTHER", name="case_status"),
            server_default="PLANNED",  # And here
            nullable=False,
        ),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["patients.id"], name=op.f("fk_cases_patient_id_patients"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cases")),
    )
    op.create_index(op.f("ix_cases_patient_id"), "cases", ["patient_id"], unique=False)
    op.create_table(
        "case_contexts",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("context_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_case_contexts_case_id_cases"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["context_id"], ["contexts.id"], name=op.f("fk_case_contexts_context_id_contexts"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("case_id", "context_id", name=op.f("pk_case_contexts")),
    )
    op.create_table(
        "case_devices",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("assigned_to", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_case_devices_case_id_cases"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_case_devices_device_id_devices"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("case_id", "device_id", "assigned_from", name=op.f("pk_case_devices")),
    )
    op.create_index(op.f("ix_case_devices_device_id"), "case_devices", ["device_id"], unique=False)
    op.create_table(
        "case_wearables",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("wearable_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("assigned_to", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_case_wearables_case_id_cases"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["wearable_id"], ["wearables.id"], name=op.f("fk_case_wearables_wearable_id_wearables"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("case_id", "wearable_id", "assigned_from", name=op.f("pk_case_wearables")),
    )
    op.create_index(op.f("ix_case_wearables_wearable_id"), "case_wearables", ["wearable_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_case_wearables_wearable_id"), table_name="case_wearables")
    op.drop_table("case_wearables")
    op.drop_index(op.f("ix_case_devices_device_id"), table_name="case_devices")
    op.drop_table("case_devices")
    op.drop_table("case_contexts")
    op.drop_index(op.f("ix_cases_patient_id"), table_name="cases")
    op.drop_table("cases")
    op.drop_table("wearables")
    op.drop_table("patients")
    op.drop_table("devices")
    op.drop_table("contexts")
    # ### end Alembic commands ###
