replicaCount: 1

image:
  repository: wearables42/wearables-extraction-service
  pullPolicy: Always
  tag: "2026-03-29"

service:
  type: ClusterIP
  port: 8010

secretRef: "extraction-service-secrets"

env:
  DB_LORD_BASE_URL: "http://db-lord.db-lord.svc.cluster.local:8080"
