apiVersion: apps/v1
kind: Deployment
metadata:
  name: importservice
  labels:
    app: importservice
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.env.KAFKA_BOOTSTRAP_SERVERS }}"
            - name: KAFKA_TOPIC
              value: "{{ .Values.env.KAFKA_TOPIC }}"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.jwtSecret.secretName }}
                  key: {{ .Values.jwtSecret.key }}
            - name: JWT_ISSUER
              value: "{{ .Values.env.JWT_ISSUER }}"
          livenessProbe:
            httpGet:
              path: "{{ .Values.livenessProbe.path }}"
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: "{{ .Values.readinessProbe.path }}"
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
