apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ .Release.Name }}-http"
spec:
  entryPoints:
    - web 
  routes:
    - match: "Host(`{{ .Values.ingress.host }}`)"
      kind: Rule
      middlewares:
      - name: redirect-to-https
        namespace: ingress
      services:
        - name: {{ .Release.Name }}
          port: {{ .Values.service.port }}