//package org.example.dependencies;
//
//import lombok.Data;
//import lombok.NoArgsConstructor;
//import org.example.config.Environment;
//import org.example.fhir.model.MappingYaml;
//import org.example.fhir.model.FieldConfig;
//import org.example.fhir.model.ValueTransformation;
//import org.slf4j.Logger;
//import org.slf4j.LoggerFactory;
//
//import java.util.*;
//
///***
// * DataBasis defines the minimal set of attributes (generating set) in storage, so that all other values can be reconstructed from it.
// */
//@Data
//public class DataBasis {
//
//    private static final Logger log = LoggerFactory.getLogger(DataBasis.class);
//
//    private Map<String, DependencyLayer> optimalSet;
//
//    public DataBasis(MappingYaml yaml) {
//        this.optimalSet = calculateBasis(yaml);
//    }
//
//    public static DataBasis getInstance() {
//        return Holder.INSTANCE;
//    }
//
//    public Set<String> getCategories() {
//        return this.optimalSet.keySet();
//    }
//
//    public Map<FieldConfig, Set<FieldConfig>> getDerivativesMap(String s) {
//        return this.optimalSet.get(s).getBaseDerivativesMap();
//    }
//
//    private static class Holder {
//        private static final DataBasis INSTANCE = new DataBasis(Environment.TEMPLATE);
//    }
//
//    private Map<String, DependencyLayer> calculateBasis(MappingYaml yaml) {
//
//        this.optimalSet = new HashMap<>();
//
//        /*
//        1. Check metadata dependencies
//        2. Check measurement dependencies
//        --> these two steps build the first layer
//        3. Check artificial dependecies
//        --> this builds the dependency tree
//        4. Check overrides
//        --> this adds all required fields that are not in the set yet
//        */
//
//        Map<String, DependencyLayer> base = new HashMap<>();
//        List<FieldConfig> metadataFields = yaml.getMetadata().getFields();
//
//        yaml.getMeasurement().getPaths().forEach(
//                x -> {
//                    Set<FieldConfig> fields = new HashSet<>();
//                    fields.addAll(x.getFields());
//                    fields.addAll(metadataFields);
//                    base.put(x.getPath(), checkFields(fields, yaml));
//                }
//        );
//
//        log.debug("Base contains {} entries", base.size());
//
//        //Afterward, we can look at the defined dependencies between the FHIR fields and recursively / transitively aggregate all dependencies of the base fields, its dependencies and their respective dependencies etc.
//
//        //TODO right now we are only considering dependencies based on the "source" field, which is enough with the refactored map for the base
//        //TODO BUT we also need to consider dependencies on fhir fields
//
//        Map<String, DependencyLayer> finalBasis = new HashMap<>();
//
//        //Fist check the base level and merge correspondingly for each category
//        for (Map.Entry<String, DependencyLayer> category : base.entrySet()) {
//            DependencyLayer d = minimizeBase(category.getValue());
//            finalBasis.put(category.getKey(), d);
//        }
//
//        //In the end we should be left with a minimal set of values
//
//        return finalBasis;
//    }
//
//    private static DependencyLayer minimizeBase(DependencyLayer category) {
//
//        boolean changed;
//
//        do {
//            changed = false;
//
//            for (Map.Entry<FieldConfig, Set<FieldConfig>> entry : category.getBaseDerivativesMap().entrySet()) {
//
//                Set<FieldConfig> toAdd = new HashSet<>();
//
//                for (FieldConfig dep : entry.getValue()) {
//                    Set<FieldConfig> depDeps = category.getBaseDerivativesMap().get(dep);
//                    if (depDeps != null) {
//                        toAdd.addAll(depDeps);
//                    }
//                }
//
//                // Only continue looping if something new was added
//                if (!entry.getValue().containsAll(toAdd)) {
//                    entry.getValue().addAll(toAdd);
//                    changed = true;
//                }
//            }
//
//        } while (changed);
//
//        return category;
//    }
//
//    /**
//     * CheckFields first checks if any of the supplied fields have the same source, and if that is the case, it calls determineBaseField. If not, a dependenyMap is created where each field is only its own base (and has no dependencies)
//     * @param fields Set of fields
//     * @param yaml YAML that specifies the mapping schema
//     * @return DependencyLayer map that specifies dependencies inside the mapping
//     */
//    private DependencyLayer checkFields(Set<FieldConfig> fields, MappingYaml yaml) {
//
//        //The only optimization we can achieve is, if two FHIR fields are generated by the same RAW field and have injective transformation
//
//        //We map all fields with the same source to that source (String -> Fields)
//        Map<String, Set<FieldConfig>> found = new HashMap<>();
//        boolean foundAny = false;
//
//        for (FieldConfig f : fields) {
//
//            if (found.containsKey(f.getSource())) {
//                //found FHIR fields that depend on the same RAW field
//                found.get(f.getSource()).add(f);
//                foundAny = true;
//
//                log.debug("Found at two fields that depend on the same source {}", f.getSource());
//            } else {
//                Set<FieldConfig> fieldsWithSource = new HashSet<>();
//                fieldsWithSource.add(f);
//                found.put(f.getSource(), fieldsWithSource);
//
//                log.debug("Found new source in fields {}", f.getSource());
//            }
//
//        }
//
//        //If no fields have any dependencies, we create a map where each field is its own key, with empty dependency sets
//        if (!foundAny) {
//
//            Map<FieldConfig, Set<FieldConfig>> noDepMap = new HashMap<>();
//
//            found.values().stream()
//                    .flatMap(Set::stream)
//                    .forEach(x -> noDepMap.put(x, new HashSet<>()));
//
//            return new DependencyLayer(noDepMap);
//        }
//
//        return determineBaseField(found, yaml);
//    }
//
//    /**
//     * determineBaseFields checks for every field that has dependencies if there is an injective field. It then chooses the one with the shortest name and takes it as a base. For fields that do not have any dependencies, it adds them to the map as their own base.
//     * @param found Fields grouped by their dependencies
//     * @param yaml YAML that specifies the mapping schema
//     * @return DependencyLayer map that specifies dependencies inside the mapping
//     */
//    private DependencyLayer determineBaseField(Map<String, Set<FieldConfig>> found, MappingYaml yaml) {
//
//        Map<FieldConfig, Set<FieldConfig>> allInjectives = new HashMap<>();
//
//        //TODO: I dont know if this is the best way to determine that we use the same tags when possible
//        found.forEach((key, value) -> {
//            FieldConfig optimalBase = value.stream()
//                    .filter(y -> y.getTransformFromRaw().stream()
//                            .allMatch(transform -> isInjective(transform, yaml)))
//                    .min(Comparator.comparingInt(x -> x.getName().length()))
//                    .orElse(null);
//
//            if (optimalBase != null) {
//                allInjectives.put(optimalBase, value);
//            } else {
//                value.forEach(
//                        x -> allInjectives.put(x, new HashSet<>())
//                );
//            }
//        });
//
//
//        /*
//        Here the map should only contain sources with the condition:
//            1. Source has >1 dependent field
//            2. At least one fields transformations are injective
//         */
//
//        return allInjectives.isEmpty() ? null : new DependencyLayer(allInjectives);
//
//    }
//
//    private boolean isInjective(ValueTransformation v, MappingYaml yaml) {
//        return false; //TODO
//    }
//
//
//}
//
//@Data
//@NoArgsConstructor
//class DependencyLayer {
//
//    DependencyLayer(Map<FieldConfig, Set<FieldConfig>> map){
//        this.baseDerivativesMap = map;
//    }
//
//    Map<FieldConfig, Set<FieldConfig>> baseDerivativesMap;
//}