image:
  repository: grafana/grafana
  tag: latest
  imagePullPolicy: IfNotPresent
container:
  port: 3000
resourceRequests:
  cpu: 1
  mem: 2Gi
persistence:
  storage: 1Gi
  storageClassName: local-path # may need to be changed accordingly
  accessModes: ["ReadWriteOnce"]
ingress: 
  host: "wearables.charite.de"
  prefix: "/grafana"
  httpOnly: false
certificate:
  name: wearables-cert
  secretName: wearables-tls
security:
  csrfTrustedOrigins: "http://localhost:3002,https://wearables.charite.de,http://wearables.charite.de"
