name: wearables_app_tub
description: "Flutter health monitoring app"
publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  health: ^10.2.0
  background_fetch: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true