replicaCount: 1

image:
  repository: gmsdaniil/wearables-web
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 80

runtimeConfigMap:
  create: true
  name: ""

runtimeConfig:
  apiBaseUrl: "/api"
  grafanaProxyUrl: "/grafana-proxy"
  socketUrl: ""

ingress:
  enabled: false
  host: "wearables.charite.de"
  
certificate:
  secretName: wearables-tls
