replicaCount: 1

image:
  repository: gmsdaniil/wearables-web
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 80

# Build-time environment variables (baked into the image)
# To change these, rebuild the image with new values
buildArgs:
  VITE_API_BASE_URL: "http://registration-service-node.registration-service-node.svc.cluster.local:3001/api"
  VITE_BACKEND_URL: ""
  VITE_GRAFANA_IFRAME_URL: "/grafana/"

ingress:
  enabled: true
  host: "wearables.charite.de"
  
certificate:
  secretName: wearables-tls
