# Default values for mosquitto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicas: 1
port: 1883

image:
  repository: eclipse-mosquitto
  tag: 2