apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretRef }}
type: Opaque
stringData:
  POSTGRES_SERVER: "{{ .Values.env.POSTGRES_SERVER | default "" }}"
  POSTGRES_PORT: "{{ .Values.env.POSTGRES_PORT | default "" }}"
  POSTGRES_DB: {{ .Values.env.POSTGRES_DB | default "" }}
  POSTGRES_USER: {{ .Values.env.POSTGRES_USER | default "" }}
  POSTGRES_PASSWORD: {{ .Values.env.POSTGRES_PASSWORD | default "" | quote }}
  INFLUX_URL: {{ .Values.env.INFLUX_URL | default "" }}
  INFLUX_ORG: {{ .Values.env.INFLUX_ORG | default "" }}
  INFLUX_BUCKET: {{ .Values.env.INFLUX_BUCKET | default "" }}
  INFLUX_TOKEN: {{ .Values.env.INFLUX_TOKEN | default "" | quote }}