apiVersion: batch/v1
kind: Job
metadata:
  name: db-lord-migrate
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["alembic", "upgrade", "head"]
          env:
            - name: POSTGRES_SERVER
              value: {{ .Values.env.POSTGRES_SERVER | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.env.POSTGRES_PORT | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.env.POSTGRES_DB | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.env.POSTGRES_USER | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRef }}
                  key: POSTGRES_PASSWORD
