apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-seaweedfs-volume-0
  namespace: seaweedfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: cinder-csi
  volumeName: pvc-d53d6734-90b2-4ba0-9b37-a0b19e0e93c5  # binds to your specific existing volume