apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-d53d6734-90b2-4ba0-9b37-a0b19e0e93c5
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cinder-csi
  csi:
    driver: cinder.csi.openstack.org
    volumeHandle: 9f343329-2b97-453a-964c-bb641cb3b70a
    fsType: ext4