apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mySecrets.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  admin_access_key_id: {{ .Values.mySecrets.adminAccessKeyId | quote }}
  admin_secret_access_key: {{ .Values.mySecrets.adminSecretAccessKey | quote }}
  read_access_key_id: {{ .Values.mySecrets.readAccessKeyId | quote }}
  read_secret_access_key: {{ .Values.mySecrets.readSecretAccessKey | quote }}
  