// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Patient & Case API
 * Endpoints for fetching read-only Hospital cases and managing internal patients/cases.  ## Frontend Flow 1. Enter a Hospital case ID (hospitalCaseId) 2. Fetch and display the external Hospital case 3. User clicks \"Create Case\" to create an internal case 4. Show that patient/case was created and store the caseId 5. Display the case token as QR code for scanning in the Hospital app  ## Existing Patient Access 1. Fetch all internal patients/cases 2. User selects a patient/case to view details 3. Display case details and show case token as QR code  ## App Flow 1. Receive a caseToken scanned from Hospital app 2. Fetch the internal case using POST /cases/verify-token 3. Display case details 4. Allow user to proceed with further actions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Case,
  Patient,
} from '../models/index';
import {
    CaseFromJSON,
    CaseToJSON,
    PatientFromJSON,
    PatientToJSON,
} from '../models/index';

export interface PatientsPatientIdCasesGetRequest {
    patientId: string;
}

export interface PatientsPatientIdGetRequest {
    patientId: string;
}

/**
 * PatientsApi - interface
 * 
 * @export
 * @interface PatientsApiInterface
 */
export interface PatientsApiInterface {
    /**
     * Returns a list of all internal patients
     * @summary List internal patients
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientsApiInterface
     */
    patientsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Patient>>>;

    /**
     * Returns a list of all internal patients
     * List internal patients
     */
    patientsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Patient>>;

    /**
     * Returns all cases linked to a specific patient
     * @summary List cases for a patient
     * @param {string} patientId Internal patient identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientsApiInterface
     */
    patientsPatientIdCasesGetRaw(requestParameters: PatientsPatientIdCasesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Case>>>;

    /**
     * Returns all cases linked to a specific patient
     * List cases for a patient
     */
    patientsPatientIdCasesGet(requestParameters: PatientsPatientIdCasesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Case>>;

    /**
     * Returns a single internal patient by ID
     * @summary Get a single patient
     * @param {string} patientId Internal patient identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientsApiInterface
     */
    patientsPatientIdGetRaw(requestParameters: PatientsPatientIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Patient>>;

    /**
     * Returns a single internal patient by ID
     * Get a single patient
     */
    patientsPatientIdGet(requestParameters: PatientsPatientIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Patient>;

}

/**
 * 
 */
export class PatientsApi extends runtime.BaseAPI implements PatientsApiInterface {

    /**
     * Returns a list of all internal patients
     * List internal patients
     */
    async patientsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Patient>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/patients`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PatientFromJSON));
    }

    /**
     * Returns a list of all internal patients
     * List internal patients
     */
    async patientsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Patient>> {
        const response = await this.patientsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns all cases linked to a specific patient
     * List cases for a patient
     */
    async patientsPatientIdCasesGetRaw(requestParameters: PatientsPatientIdCasesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Case>>> {
        if (requestParameters['patientId'] == null) {
            throw new runtime.RequiredError(
                'patientId',
                'Required parameter "patientId" was null or undefined when calling patientsPatientIdCasesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/patients/{patientId}/cases`;
        urlPath = urlPath.replace(`{${"patientId"}}`, encodeURIComponent(String(requestParameters['patientId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CaseFromJSON));
    }

    /**
     * Returns all cases linked to a specific patient
     * List cases for a patient
     */
    async patientsPatientIdCasesGet(requestParameters: PatientsPatientIdCasesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Case>> {
        const response = await this.patientsPatientIdCasesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a single internal patient by ID
     * Get a single patient
     */
    async patientsPatientIdGetRaw(requestParameters: PatientsPatientIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Patient>> {
        if (requestParameters['patientId'] == null) {
            throw new runtime.RequiredError(
                'patientId',
                'Required parameter "patientId" was null or undefined when calling patientsPatientIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/patients/{patientId}`;
        urlPath = urlPath.replace(`{${"patientId"}}`, encodeURIComponent(String(requestParameters['patientId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PatientFromJSON(jsonValue));
    }

    /**
     * Returns a single internal patient by ID
     * Get a single patient
     */
    async patientsPatientIdGet(requestParameters: PatientsPatientIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Patient> {
        const response = await this.patientsPatientIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
