# UUID/string field lengths
PATIENT_NAME_MAX_LEN = 256
PATIENT_SEX_MAX_LEN = 32

HARDWARE_SERIAL_MAX_LEN = 128
HARDWARE_MODEL_MAX_LEN = 128
HARDWARE_MANUFACTURER_MAX_LEN = 128
HARDWARE_OS_VERSION_MAX_LEN = 128

CONTEXT_GROUP_NAME_MAX_LEN = 2048
CONTEXT_COORDINATOR_MAX_LEN = 256

FHIR_VERSION_MAX_LEN = 128
FHIR_CATEGORY_MAX_LEN = 128

# Numeric precision/scale
PATIENT_WEIGHT_PRECISION = 5
PATIENT_WEIGHT_SCALE = 2
PATIENT_HEIGHT_PRECISION = 5
PATIENT_HEIGHT_SCALE = 2

API_TOKEN_HASH_LEN = 64  # hex sha256
API_TOKEN_NAME_MAX_LEN = 100
API_TOKEN_OWNER_MAX_LEN = 320  # email
