// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Patient & Case API
 * Endpoints for fetching read-only Hospital cases and managing internal patients/cases.  ## Frontend Flow 1. Enter a Hospital case ID (hospitalCaseId) 2. Fetch and display the external Hospital case 3. User clicks \"Create Case\" to create an internal case 4. Show that patient/case was created and store the caseId 5. Display the case token as QR code for scanning in the Hospital app  ## Existing Patient Access 1. Fetch all internal patients/cases 2. User selects a patient/case to view details 3. Display case details and show case token as QR code  ## App Flow 1. Receive a caseToken scanned from Hospital app 2. Fetch the internal case using POST /cases/verify-token 3. Display case details 4. Allow user to proceed with further actions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CasesFromHospitalCasePostRequest
 */
export interface CasesFromHospitalCasePostRequest {
    /**
     * Hospital case identifier
     * @type {string}
     * @memberof CasesFromHospitalCasePostRequest
     */
    hospitalCaseId: string;
}

/**
 * Check if a given object implements the CasesFromHospitalCasePostRequest interface.
 */
export function instanceOfCasesFromHospitalCasePostRequest(value: object): value is CasesFromHospitalCasePostRequest {
    if (!('hospitalCaseId' in value) || value['hospitalCaseId'] === undefined) return false;
    return true;
}

export function CasesFromHospitalCasePostRequestFromJSON(json: any): CasesFromHospitalCasePostRequest {
    return CasesFromHospitalCasePostRequestFromJSONTyped(json, false);
}

export function CasesFromHospitalCasePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CasesFromHospitalCasePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'hospitalCaseId': json['hospitalCaseId'],
    };
}

export function CasesFromHospitalCasePostRequestToJSON(json: any): CasesFromHospitalCasePostRequest {
    return CasesFromHospitalCasePostRequestToJSONTyped(json, false);
}

export function CasesFromHospitalCasePostRequestToJSONTyped(value?: CasesFromHospitalCasePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hospitalCaseId': value['hospitalCaseId'],
    };
}

