// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Patient & Case API
 * Endpoints for fetching read-only Hospital cases and managing internal patients/cases.  ## Frontend Flow 1. Enter a Hospital case ID (hospitalCaseId) 2. Fetch and display the external Hospital case 3. User clicks \"Create Case\" to create an internal case 4. Show that patient/case was created and store the caseId 5. Display the case token as QR code for scanning in the Hospital app  ## Existing Patient Access 1. Fetch all internal patients/cases 2. User selects a patient/case to view details 3. Display case details and show case token as QR code  ## App Flow 1. Receive a caseToken scanned from Hospital app 2. Fetch the internal case using POST /cases/verify-token 3. Display case details 4. Allow user to proceed with further actions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Case
 */
export interface Case {
    /**
     * Internal case identifier
     * @type {string}
     * @memberof Case
     */
    caseId: string;
    /**
     * Associated patient identifier
     * @type {string}
     * @memberof Case
     */
    patientId: string;
    /**
     * Original Hospital case identifier
     * @type {string}
     * @memberof Case
     */
    hospitalCaseId?: string;
    /**
     * Case status
     * @type {string}
     * @memberof Case
     */
    status: CaseStatusEnum;
    /**
     * JWT token for case access
     * @type {string}
     * @memberof Case
     */
    caseToken?: string | null;
}


/**
 * @export
 */
export const CaseStatusEnum = {
    active: 'active',
    inactive: 'inactive'
} as const;
export type CaseStatusEnum = typeof CaseStatusEnum[keyof typeof CaseStatusEnum];


/**
 * Check if a given object implements the Case interface.
 */
export function instanceOfCase(value: object): value is Case {
    if (!('caseId' in value) || value['caseId'] === undefined) return false;
    if (!('patientId' in value) || value['patientId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function CaseFromJSON(json: any): Case {
    return CaseFromJSONTyped(json, false);
}

export function CaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Case {
    if (json == null) {
        return json;
    }
    return {
        
        'caseId': json['caseId'],
        'patientId': json['patientId'],
        'hospitalCaseId': json['hospitalCaseId'] == null ? undefined : json['hospitalCaseId'],
        'status': json['status'],
        'caseToken': json['caseToken'] == null ? undefined : json['caseToken'],
    };
}

export function CaseToJSON(json: any): Case {
    return CaseToJSONTyped(json, false);
}

export function CaseToJSONTyped(value?: Case | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'caseId': value['caseId'],
        'patientId': value['patientId'],
        'hospitalCaseId': value['hospitalCaseId'],
        'status': value['status'],
        'caseToken': value['caseToken'],
    };
}

